name: admin_app
description: One of One admin operations console.
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.10.4"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.8.0
  core_ui:
    path: ../../packages/core_ui
  data:
    path: ../../packages/data
  domain:
    path: ../../packages/domain
  services:
    path: ../../packages/services
  utils:
    path: ../../packages/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
